name: release-chart

on:
  workflow_call:
    inputs:
      OWNER:
        required: true
        type: string
      REPOSITORY:
        required: true
        type: string
      BRANCH:  
        required: true
        type: string
jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
      with:
        path: main

    - name: Clone Helm Charts Repo
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}
        path: ${{ inputs.REPOSITORY }}

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.8.1

    - name: Publish Chart
      run: |
        CHART_VERSION=$(cat charts/${{ inputs.PROJECT }}/Chart.yaml | grep version | awk '{print $2}' )
        helm package ${ GITHUB_WORKSPACE }/main/charts/${{ inputs.PROJECT }}
        mv ${{ inputs.PROJECT }}-${ CHART_VERSION }.tgz ${ GITHUB_WORKSPACE }/${{ inputs.REPOSITORY }}
        cd ${ GITHUB_WORKSPACE }/${{ inputs.REPOSITORY }}
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git push origin {{ inputs.BRANCH }}
