name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

env:
  PROJECT: argo-ecr-auth    

jobs:

  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      PROJECT: ${{ env.PROJECT }}
    secrets: inherit
